demo01/booklist/urls.py
from django.conf.urls import url

from . import views

# 去除硬编码（名称任意，但是需要与命名空间的名称一致，一般取名为项目名称）
app_name = "booklist"
# 去除硬编码 在应用的urlconf中添加url别名(name=)
urlpatterns = [
    # url('index/', views.index),
    # url('index/$', views.index),
    url(r'^$', views.index, name='index'),
    url(r'^booklist/$', views.list, name='list'),
    # url(r'$', views.index),
    url(r'^bookdetail/(\d+)/$', views.detail, name='detail'),
    url(r'^bookinfoss/(\d+)/$', views.infoss, name='infoss'),
    url(r'^add/$', views.add, name='add'),
    url(r'^delete/(\d+)/$', views.delete, name='delete'),
]

demo01/demo01/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    # 去除硬编码 在项目的urls.py中指定应用的命名空间 与app_name中的名称一致
    url('booklist/', include('booklist.urls', namespace="booklist")),
    url('votes/', include('votes.urls')),
]


'''
项目网址
通过urlpatterns列表中的内容将路由和视图绑定
'''

demo01/votes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.lists),
    url(r'^ends/(\d+)/$', views.ends),
    url(r'^counts/(\d+)/$', views.counts),
]

demo01/booklist/models.py
from django.db import models


class BookInfo(models.Model):
    bname = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.bname


class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=100)
    # 外键 第一个参数为表名 第二个参数代表删除类型
    hbook = models.ForeignKey('BookInfo', on_delete=models.CASCADE)

    def __str__(self):
        return self.hname

    def skills(self):
        return self.hcontent

    skills.short_description = '描述'

    def name(self):
        return self.hname

    name.short_description = '名称'


    # def
# Create your models here.

'''
django MVT M
ORM 对象中O
定义模型：继承models.Model
配置数据库：默认的是SQLite
将应用名添加到应用列表installed_apps

python manage.py makemigrations 生成迁移文件
python manage.py migrate 执行迁移
'''
'''
python manage.py shell进入命令：不需要运行项目就可以操作数据库
导入类来自bootlist.models 导入HeroInfo,BookInfo
查找所有行表民.objects.all()
根据主键查找表名.objects.get(pk=1)
添加对象 对象.save()
修改对象 对象.save()
删除对象 对象.delete()
一对多：一方存在主键 ，多方存在主键也存在外键（一方中主键）
一方.heroinfo_set.all()
类名.object.create(列名=值)不需要保存
'''

demo01/votes/models.py
from django.db import models

# Create your models here.


class Questions(models.Model):
    qcontain = models.CharField(max_length=100)

    def __str__(self):
        return self.qcontain


class Choices(models.Model):
    cchoose = models.CharField(max_length=20)
    ccount = models.IntegerField(default=0)
    cvalues = models.ForeignKey('Questions', on_delete=models.CASCADE)

demo01/booklist/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from .models import BookInfo, HeroInfo


# Create your views here.

# 定义视图函数


def index(request):
    # print("请求", request)
    # return HttpResponse("首页")
    # print('首页')
    # # 加载模板
    # indextem = loader.get_template('books/index.html')
    # cont = {'username': 'Shirlesha'}
    # # 使用变量参数渲染模板
    # result = indextem.render(cont)
    # # 返回模板
    # return HttpResponse(result)
    return render(request, template_name='books/index.html', context={'username': 'Shirlesha'})


def list(request):
    # # return HttpResponse("列表页")
    # listtem = loader.get_template('books/list.html')
    # cont = {}
    # result = listtem.render(cont)
    # return HttpResponse(result)
    return render(request, template_name='books/list.html', context={'books': BookInfo.objects.all()})


def detail(request, id):
    # # try:
    # #     b = BookInfo.objects.get(pk=id)
    # #     return HttpResponse(b)
    # # except:
    # #     return HttpResponse("书名不存在")
    # detailtem = loader.get_template('books/detail.html')
    # cont = {}
    # result = detailtem.render(cont)
    # return HttpResponse(result)
    books = BookInfo.objects.get(pk=id)
    return render(request, template_name='books/detail.html', context={'books': books})


def infoss(request, id):
    roles = HeroInfo.objects.get(pk=id)
    return render(request, template_name='books/infoss.html', context={'roles': roles})


def add(request):
    # BookInfo.add_to_class(bookname)
    # return HttpResponse("添加成功")
    books = request.POST['bookname']
    return HttpResponse("添加成功")

    print(books)
    # book = BookInfo()
    #     # book.bname = books
    #     # book.bpub_date = datetime.datetime
    #     # print(book.bpub_date)
    return render(request, template_name='books/add.html', context={'books': BookInfo.objects.all()})


def delete(request, id):
    # print(BookInfo.objects.get(pk=id))
    # BookInfo.objects.get(pk=id).delete()
    # return HttpResponseRedirect('books/list.html', {'books': BookInfo.objects.all()})
    # # return render(request, template_name='books/list.html', context={'books': BookInfo.objects.all()})
    try:
        BookInfo.objects.get(pk=id).delete()
        bl = BookInfo.objects.all()
        # 使用render没有刷新请求url
        # return render(request, 'booktest/list.html', {"booklist": bl})
        # 重新向服务器发起请求 刷新url
        # 这里不知道为什么不可以去除硬编码
        return HttpResponseRedirect('/booklist/booklist/', {"booklist": bl})
    except:
        return HttpResponse("删除失败")

'''
视图函数
将函数和路由绑定
'''

demo01/votes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .models import Questions, Choices


# Create your views here.
# 定义视图函数


def lists(request):
    return render(request, template_name='votess/lists.html', context={'listss': Questions.objects.all()})


def ends(request, id):
    endss = Questions.objects.get(pk=id)
    return render(request, template_name='votess/ends.html', context={'endss': endss})


def counts(request, id):

    # print('aadsgad')
    # return HttpResponse('hello')
    endss = Questions.objects.get(pk=id)
    print(endss)

    count = request.POST['choo']
    print(count)
    # print('aadsgad')
    # return HttpResponse('hello')
    chooo = Choices.objects.get(pk=count)
    print(chooo)
    chooo.ccount += 1
    chooo.save()
    # return render(request, template_name='votess/counts.html', context={'endss': endss})
    return HttpResponseRedirect('/votes/counts/endss.id/', context={'endss': endss})

demo01/templates/books/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
    {# 解除硬编码 #}
    {% load static from staticfiles %}
    {#<link rel="stylesheet" href="/static/css/models.css">#}
    <link rel="stylesheet" href="{% static '/css/models.css'%}">
</head>
<body>
    <div class="container">
        <form action="{% url 'booklist:add' %}" method="POST">
        图书名字：<input name="bookname" value="" type="text" placeholder="请输入您要添加的书名"><br>
        <input type="submit" value="添加">
    </form>
    </div>
</body>
</html>

demo01/templates/books/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    {# 解除硬编码 #}
    {% load static from staticfiles %}
    {#<link rel="stylesheet" href="/static/css/models.css">#}
    <link rel="stylesheet" href="{% static '/css/models.css'%}">
</head>
<body>
    <div class="container">
        <h2>书名:{{books.bname}}</h2>
        <ul>
            <h3>角色及简介</h3>
            {% for hero in books.heroinfo_set.all %}
                {#<li><a href="/booklist/infoss/{{hero.id}}">{{hero.hname}}</a>-------------{{hero.hcontent}}</li>#}
                {# 去除硬编码 去除模块硬编码 #}
                <li><a href="{%url 'booklist:infoss' hero.id%}">{{hero.hname}}</a>-------------{{hero.hcontent}}</li>

            {% empty %}
                <h3>请添加角色</h3>
            {% endfor %}
        </ul>
        {#<a href="/booklist/list">返回列表页</a>#}
        <a href="{%url 'booklist:list'%}">返回列表页</a>
    </div>
</body>
</html>

demo01/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    {# 解除硬编码 #}
    {% load static from staticfiles %}
    {#<link rel="stylesheet" href="/static/css/models.css">#}
    <link rel="stylesheet" href="{% static '/css/models.css'%}">

</head>
<body>
    <div class="container">
        
        {% if username %}
        <h2>欢迎您：{{username}}</h2>
        {#<a href="/booklist/list/">查看图书列表</a>#}
        <a href="{%url 'booklist:list'%}">查看图书列表</a>
        {#<img src="/static/images/c5.jpg" alt="">#}
        <img src="{% static '/images/c5.jpg'%}" alt="">

        {% else %}
            <h2>请登录</h2>
        {% endif%}
    </div>
</body>
</html>

demo01/templates/books/infoss.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详细信息</title>
    {% load static from staticfiles%}
    {#<link rel="stylesheet" href="/static/css/models.css">#}
    <link rel="stylesheet" href="{% static '/css/models.css'%}">
</head>
<body>
    <div class="container">
        <h2>角色及简介</h2>
        <ul>
            <li>
                <h4>人物：{{roles}}</h4>
            </li>
            <li>
                {% if roles.hgender %}
                    <h4>性别：男</h4>
                {% else %}
                    <h4>性别：女</h4>
                {% endif %}
            </li>
            <li>
                <h4>描述：{{roles.hcontent}}</h4>
            </li>
            <li>
                <h4>所在书籍：{{roles.hbook}}</h4>
            </li>
        </ul>
        <a href="{% url 'booklist:list'%}">返回列表页</a>
    </div>
</body>
</html>

demo01/templates/books/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>

   {# 解除硬编码 #}
    {% load static from staticfiles %}
    {#<link rel="stylesheet" href="/static/css/models.css">#}
    <link rel="stylesheet" href="{% static '/css/models.css'%}">

</head>
<body>
    <div class="container">
        <ul>
            <h2>图书列表页</h2>
            {% for book in books%}

            {#<li><a href="/booklist/detail/{{book.id}}/">{{book.bname}}</a></li>#}
            <li><a href="{%url 'booklist:detail' book.id%}">{{book.bname}}</a><a href="{%url 'booklist:delete' book.id%}">删除书籍</a>
            </li>
            {% empty %}
                <h2>这里还没有图书哦</h2>
            {% endfor %}
        </ul>
        <a href="{%url 'booklist:add' %}">添加书籍</a>
        {#<a href="/booklist/">返回首页</a>#}
        <a href="{% url 'booklist:index'%}">返回首页</a>
    </div>
</body>
</html>

demo01/templates/votess/counts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>结果页面</title>
    <link rel="stylesheet" href="/static/css/models.css">
</head>
<body>
    <div class="container">
        <h2>投票结果</h2>
        <h3>{{endss.qcontain}}</h3>
        <ul>
            {% for answers in endss.choices_set.all %}
                <li>{{answers.cchoose}} --&nbsp; &nbsp;-->{{answers.ccount}}票</li>
            {% empty %}
                <h4>没有选项</h4>
            {% endfor %}
        </ul>
        <a href="/votes">返回问题列表</a>
    </div>
</body>
</html>

demo01/templates/votess/ends.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票页面</title>
    <link rel="stylesheet" href="/static/css/models.css">
</head>
<body>
    <div class="container">
        <h2>请做出您的选择：</h2>
        <h3>{{endss.qcontain}}</h3>
        <ul>
            <form action="/votes/counts/{{endss.id}}/" method="POST">
                {% for answers in endss.choices_set.all %}

                    <li><input type="radio" name="choo" value="{{answers.id}}">{{answers.cchoose}}</li>

                {% empty %}
                    <h4>没有选项</h4>
                {% endfor %}
                <input type="submit" value="确定">
            </form>
        </ul>
        <a href="/votes">返回问题列表</a>
    </div>
</body>
</html>

demo01/templates/votess/lists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问题页面</title>
        <link rel="stylesheet" href="/static/css/models.css">
</head>
<body>
    <div class="container">
        <h2>请选择您要作答的问题</h2>
        <ul>
            {% for list in listss %}
                <li>
                    <a href="/votes/ends/{{list.id}}">{{list}}</a>
                </li>
            {% empty %}
                <h4>咦，这里居然没有问题</h4>
            {% endfor %}
        </ul>
    </div>
</body>
</html>